/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.gephi.statistics.plugin;

import javax.swing.JPanel;
import org.bapedis.core.spi.algo.Algorithm;
import org.bapedis.core.spi.algo.AlgorithmSetupUI;

/**
 *
 * @author Home
 */
public class GraphDistancePanel extends javax.swing.JPanel implements AlgorithmSetupUI{
    
    private GraphDistance algo;
    /**
     * Creates new form GraphDistancePanel1
     */
    public GraphDistancePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        normalizeButton = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(normalizeButton, org.openide.util.NbBundle.getMessage(GraphDistancePanel.class, "GraphDistancePanel.normalizeButton.text_1")); // NOI18N
        normalizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalizeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(normalizeButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void normalizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalizeButtonActionPerformed
        if (algo != null)
            algo.setNormalized(normalizeButton.isSelected());
    }//GEN-LAST:event_normalizeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox normalizeButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getEditPanel(Algorithm algo) {       
        this.algo = (GraphDistance)algo;
        normalizeButton.setSelected(this.algo.isNormalized());
        return this;
    }
}
