/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.spi.alg.impl;

import java.awt.Cursor;
import java.io.File;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bapedis.core.spi.alg.Algorithm;
import org.bapedis.core.spi.alg.AlgorithmSetupUI;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;

/**
 *
 * @author Loge
 */
public class EmbeddingQuerySeqPanel extends javax.swing.JPanel implements AlgorithmSetupUI {

    /**
     * Creates new form EmbeddingQuerySeqPanel
     */
    private JFileChooser chooser;
    private File inputFile;
    private DefaultListModel<String> listModel1, listModel2;

    private EmbeddingQuerySeqAlg embeddingAlg;

    public EmbeddingQuerySeqPanel() {
        initComponents();

        listModel1 = new DefaultListModel<>();
        listModel2 = new DefaultListModel<>();

        jList1.setModel(listModel1);
        jList2.setModel(listModel2);
        jLabel5.setText(NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jLabel5.text", listModel1.size()));
        jLabel6.setText(NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jLabel6.text", listModel2.size()));
        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Open FASTA file");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("FASTA format (*.fasta)", "fasta");
        chooser.addChoosableFileFilter(fileFilter);
        chooser.setFileFilter(fileFilter);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topPanel = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        bottomPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        topPanel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton1, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jRadioButton1.text")); // NOI18N
        topPanel.add(jRadioButton1, new java.awt.GridBagConstraints());

        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton2, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jRadioButton2.text")); // NOI18N
        topPanel.add(jRadioButton2, new java.awt.GridBagConstraints());

        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton3, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jRadioButton3.text")); // NOI18N
        topPanel.add(jRadioButton3, new java.awt.GridBagConstraints());

        org.openide.awt.Mnemonics.setLocalizedText(jRadioButton4, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jRadioButton4.text")); // NOI18N
        topPanel.add(jRadioButton4, new java.awt.GridBagConstraints());

        add(topPanel, java.awt.BorderLayout.NORTH);

        bottomPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.bottomPanel.border.title"))); // NOI18N
        bottomPanel.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jLabel3.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        bottomPanel.add(jLabel3, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jLabel4.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        bottomPanel.add(jLabel4, gridBagConstraints);

        jList1.setPreferredSize(new java.awt.Dimension(230, 0));
        jScrollPane1.setViewportView(jList1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        bottomPanel.add(jScrollPane1, gridBagConstraints);

        jList2.setPreferredSize(new java.awt.Dimension(230, 0));
        jScrollPane2.setViewportView(jList2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        bottomPanel.add(jScrollPane2, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel5, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jLabel5.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        bottomPanel.add(jLabel5, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel6, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jLabel6.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        bottomPanel.add(jLabel6, gridBagConstraints);

        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jToolBar1.setRollover(true);

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        org.openide.awt.Mnemonics.setLocalizedText(jButton2, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);
        jToolBar1.add(jSeparator1);

        org.openide.awt.Mnemonics.setLocalizedText(jButton3, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jButton3.text")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        org.openide.awt.Mnemonics.setLocalizedText(jButton4, org.openide.util.NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingQuerySeqPanel.jButton4.text")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        bottomPanel.add(jToolBar1, gridBagConstraints);

        add(bottomPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        button1Action();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jList1.setSelectionInterval(0, listModel1.getSize() - 1);
        button1Action();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        button2Action();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jList2.setSelectionInterval(0, listModel2.getSize() - 1);
        button2Action();
    }//GEN-LAST:event_jButton4ActionPerformed

    @Override
    public JPanel getSettingPanel(Algorithm algo) {
        embeddingAlg = (EmbeddingQuerySeqAlg) algo;
        listModel1.clear();
        for (String ds : embeddingAlg.selected.keySet()) {
            listModel1.addElement(ds);
        }
        
        listModel2.clear();
        for (String ds : embeddingAlg.nonSelected.keySet()) {
            listModel2.addElement(ds);
        }
        return this;
    }

    private void button1Action() {
        int[] indices = jList1.getSelectedIndices();
        for (int i = 0; i < indices.length; i++) {
            embeddingAlg.remove(listModel1.get(indices[i]));
        }
        moveFromTo(indices, listModel1, listModel2);
    }

    private void button2Action() {
        int[] indices = jList2.getSelectedIndices();
        for (int i = 0; i < indices.length; i++) {
            embeddingAlg.recover(listModel2.get(indices[i]));
        }
        moveFromTo(indices, listModel2, listModel1);
    }

    private void moveFromTo(int[] indices, DefaultListModel<String> srcModel, DefaultListModel<String> desModel) {
        for (int i = indices.length - 1; i >= 0; i--) {
            int j = 0;
            while (j < desModel.getSize() && srcModel.get(indices[i]).compareTo(desModel.get(j)) > 0) {
                j++;
            }
            desModel.insertElementAt(srcModel.get(indices[i]), j);
            srcModel.removeElementAt(indices[i]);
            jLabel5.setText(NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingAlgorithmPanel.jLabel5.text", listModel1.size()));
            jLabel6.setText(NbBundle.getMessage(EmbeddingQuerySeqPanel.class, "EmbeddingAlgorithmPanel.jLabel6.text", listModel2.size()));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables
}
