/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.spi.alg.impl;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import org.bapedis.core.spi.alg.Algorithm;
import org.bapedis.core.spi.alg.AlgorithmSetupUI;

/**
 *
 * @author loge
 */
public class FeatureSEFilteringPanel extends javax.swing.JPanel implements AlgorithmSetupUI, PropertyChangeListener {

    private FeatureSEFiltering algorithm;

    public FeatureSEFilteringPanel() {
        initComponents();

        //Configure correlation methods
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (String method : FeatureSEFiltering.CORRELATION_METHODS) {
            model.addElement(method);
        }
        redundantComboBox.setModel(model);
        redundantComboBox.setSelectedIndex(FeatureSEFiltering.CORRELATION_DEFAULT_INDEX);
    }
    
    private void refreshState() {
        boolean running = algorithm != null && algorithm.isRunning();
        boolean enabled = !running && isEnabled();
        jResetButton.setEnabled(enabled);

        jRB_selectAll.setEnabled(enabled);
        jRB_selectTop.setEnabled(enabled);
        jRB_remove.setEnabled(enabled);
        jRB_mean.setEnabled(enabled);
        jTF_top.setEnabled(enabled);
        jTF_bottom.setEnabled(enabled);

        redundantComboBox.setEnabled(enabled);
        jLabelThreshodl.setEnabled(enabled);
        jTF_corr.setEnabled(enabled);
    }

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled); //To change body of generated methods, choose Tools | Templates.
        refreshState();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jResetButton = new javax.swing.JButton();
        rankingOutputPanel = new javax.swing.JPanel();
        jRB_selectAll = new javax.swing.JRadioButton();
        jRB_selectTop = new javax.swing.JRadioButton();
        jRB_remove = new javax.swing.JRadioButton();
        jTF_top = new javax.swing.JTextField();
        jTF_bottom = new javax.swing.JTextField();
        jRB_mean = new javax.swing.JRadioButton();
        infoSEThreshold = new javax.swing.JLabel();
        redundancyPanel = new javax.swing.JPanel();
        redundantComboBox = new javax.swing.JComboBox<>();
        jLabelThreshodl = new javax.swing.JLabel();
        jTF_corr = new javax.swing.JTextField();
        histogramPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(440, 380));
        setPreferredSize(new java.awt.Dimension(440, 280));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jResetButton, org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jResetButton.text")); // NOI18N
        jResetButton.setMaximumSize(new java.awt.Dimension(145, 23));
        jResetButton.setMinimumSize(new java.awt.Dimension(145, 23));
        jResetButton.setPreferredSize(new java.awt.Dimension(145, 23));
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 5, 5);
        add(jResetButton, gridBagConstraints);

        rankingOutputPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.rankingOutputPanel.border.title"))); // NOI18N
        rankingOutputPanel.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jRB_selectAll);
        org.openide.awt.Mnemonics.setLocalizedText(jRB_selectAll, org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jRB_selectAll.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 0, 0);
        rankingOutputPanel.add(jRB_selectAll, gridBagConstraints);

        buttonGroup1.add(jRB_selectTop);
        org.openide.awt.Mnemonics.setLocalizedText(jRB_selectTop, org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jRB_selectTop.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 0, 0);
        rankingOutputPanel.add(jRB_selectTop, gridBagConstraints);

        buttonGroup1.add(jRB_remove);
        org.openide.awt.Mnemonics.setLocalizedText(jRB_remove, org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jRB_remove.text")); // NOI18N
        jRB_remove.setToolTipText(org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jRB_remove.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 0, 0);
        rankingOutputPanel.add(jRB_remove, gridBagConstraints);

        jTF_top.setText(org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jTF_top.text")); // NOI18N
        jTF_top.setPreferredSize(new java.awt.Dimension(90, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        rankingOutputPanel.add(jTF_top, gridBagConstraints);

        jTF_bottom.setText(org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jTF_bottom.text")); // NOI18N
        jTF_bottom.setPreferredSize(new java.awt.Dimension(90, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        rankingOutputPanel.add(jTF_bottom, gridBagConstraints);

        buttonGroup1.add(jRB_mean);
        org.openide.awt.Mnemonics.setLocalizedText(jRB_mean, org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jRB_mean.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 0, 0);
        rankingOutputPanel.add(jRB_mean, gridBagConstraints);

        infoSEThreshold.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/core/resources/info.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(infoSEThreshold, org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.infoSEThreshold.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        rankingOutputPanel.add(infoSEThreshold, gridBagConstraints);

        redundancyPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.redundancyPanel.border.title"))); // NOI18N
        redundancyPanel.setLayout(new java.awt.GridBagLayout());

        redundantComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redundantComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        redundancyPanel.add(redundantComboBox, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabelThreshodl, org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jLabelThreshodl.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        redundancyPanel.add(jLabelThreshodl, gridBagConstraints);

        jTF_corr.setText(org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.jTF_corr.text")); // NOI18N
        jTF_corr.setPreferredSize(new java.awt.Dimension(90, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        redundancyPanel.add(jTF_corr, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        rankingOutputPanel.add(redundancyPanel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        add(rankingOutputPanel, gridBagConstraints);

        histogramPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(FeatureSEFilteringPanel.class, "FeatureSEFilteringPanel.histogramPanel.border.title"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(histogramPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        setOption(FeatureSEFiltering.RANKING_DEFAULT_OPTION);
        
        
        redundantComboBox.setSelectedIndex(FeatureSEFiltering.CORRELATION_DEFAULT_INDEX);
        jTF_corr.setText(String.valueOf(FeatureSEFiltering.CORRELATION_DEFAULT_VALUE));
        
    }//GEN-LAST:event_jResetButtonActionPerformed

    private void redundantComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redundantComboBoxActionPerformed
        if (algorithm != null && algorithm.getCorrelationIndex() != redundantComboBox.getSelectedIndex()) {
            algorithm.setCorrelationIndex(redundantComboBox.getSelectedIndex());
        }
    }//GEN-LAST:event_redundantComboBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel histogramPanel;
    private javax.swing.JLabel infoSEThreshold;
    private javax.swing.JLabel jLabelThreshodl;
    private javax.swing.JRadioButton jRB_mean;
    private javax.swing.JRadioButton jRB_remove;
    private javax.swing.JRadioButton jRB_selectAll;
    private javax.swing.JRadioButton jRB_selectTop;
    private javax.swing.JButton jResetButton;
    private javax.swing.JTextField jTF_bottom;
    private javax.swing.JTextField jTF_corr;
    private javax.swing.JTextField jTF_top;
    private javax.swing.JPanel rankingOutputPanel;
    private javax.swing.JPanel redundancyPanel;
    private javax.swing.JComboBox<String> redundantComboBox;
    // End of variables declaration//GEN-END:variables

    private void setOption(int option){
        switch (option) {
            case FeatureSEFiltering.RANKING_SELECT_ALL:
                jRB_selectAll.setSelected(true);
                break;
            case FeatureSEFiltering.RANKING_SELECT_TOP:
                jRB_selectTop.setSelected(true);
                break;
            case FeatureSEFiltering.RANKING_REMOVE_BOTTOM:
                jRB_remove.setSelected(true);
                break;
            case FeatureSEFiltering.RANKING_MEAN_STD:
                jRB_mean.setSelected(true);
                break;
        }        
    }
    
    @Override
    public JPanel getSettingPanel(Algorithm algo) {
        this.algorithm = (FeatureSEFiltering) algo;
        setOption(algorithm.getEntropyOption());

        redundantComboBox.setSelectedIndex(this.algorithm.getCorrelationIndex());

        float val = this.algorithm.getCorrelationCutoff();
        jTF_corr.setText(String.valueOf(val));

        addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                algorithm.addPropertyChangeListener(FeatureSEFilteringPanel.this);
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
                algorithm.removePropertyChangeListener(FeatureSEFilteringPanel.this);
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });

        refreshState();

        return this;
    }

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getSource().equals(algorithm) && evt.getPropertyName().equals(FeatureSEFiltering.RUNNING)) {
            refreshState();
        }
    }

}
