/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.spi.alg.impl;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.bapedis.core.spi.alg.Algorithm;
import org.bapedis.core.spi.alg.AlgorithmSetupUI;

/**
 *
 * @author Loge
 */
public class FilteringSubsetOptimizationSetupUI extends javax.swing.JPanel implements AlgorithmSetupUI {

    /**
     * Creates new form FilteringSubsetOptimizationSetupUI
     */
    private FilteringSubsetOptimization featureSelection;
    private JPanel firstStagePanel, secondStagePanel;
    
    public FilteringSubsetOptimizationSetupUI() {
        initComponents();
    }   
         
    private void setupPanel(JPanel stagePanel, JPanel parentPanel){
        parentPanel.removeAll();
        parentPanel.add(stagePanel, BorderLayout.CENTER);
        parentPanel.revalidate();
        parentPanel.repaint();    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        filteringPanel = new javax.swing.JPanel();
        centerPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        filteringPanel.setLayout(new java.awt.GridBagLayout());

        centerPanel1.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        filteringPanel.add(centerPanel1, gridBagConstraints);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(FilteringSubsetOptimizationSetupUI.class, "FilteringSubsetOptimizationSetupUI.filteringPanel.TabConstraints.tabTitle"), filteringPanel); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jTabbedPane1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getSettingPanel(Algorithm algo) {
        featureSelection = (FilteringSubsetOptimization) algo;
               
        //Filtering algorithm
        Algorithm alg = featureSelection.getFilteringAlg();
        firstStagePanel = alg.getFactory().getSetupUI().getSettingPanel(alg);
        setupPanel(firstStagePanel, centerPanel1);
        
        //Subset optimization algorithm
//        alg = featureSelection.getSubsetOptimizationAlg();
//        secondStagePanel = alg.getFactory().getSetupUI().getSettingPanel(alg);
//        setupPanel(secondStagePanel, centerPanel2);
//        secondStagePanel.setEnabled(jcbSubsetOptimization.isSelected());
//        jcbSubsetOptimization.setSelected(featureSelection.isSecondStage());
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel1;
    private javax.swing.JPanel filteringPanel;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}