/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.network.impl;

import java.awt.BorderLayout;
import java.util.Collection;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import org.bapedis.core.model.AttributesModel;
import org.bapedis.core.services.ProjectManager;
import org.bapedis.core.spi.algo.Algorithm;
import org.bapedis.core.spi.algo.AlgorithmSetupUI;
import org.bapedis.core.ui.components.DescriptorSelectionPanel;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;

/**
 *
 * @author loge
 */
public class ChemicalSpaceNetworkPanel extends javax.swing.JPanel implements AlgorithmSetupUI, LookupListener {

    /**
     * Creates new form ChemicalSpaceNetworkPanel
     */
    protected ChemicalSpaceNetwork csnAlgo;
    protected final ThresholdRangePanel thresholdPanel;
    protected final ProjectManager pc;
    Lookup.Result<AttributesModel> peptideLkpResult;

    public ChemicalSpaceNetworkPanel() {
        initComponents();
        pc = Lookup.getDefault().lookup(ProjectManager.class);
        thresholdPanel = new ThresholdRangePanel();
        southPanel.add(thresholdPanel, BorderLayout.CENTER);

        addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                peptideLkpResult = pc.getCurrentWorkspace().getLookup().lookupResult(AttributesModel.class);
                peptideLkpResult.addLookupListener(ChemicalSpaceNetworkPanel.this);
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
                if (peptideLkpResult != null) {
                    peptideLkpResult.removeLookupListener(ChemicalSpaceNetworkPanel.this);
                    peptideLkpResult = null;
                }
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        descriptorsPanel = new javax.swing.JPanel();
        southPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        descriptorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ChemicalSpaceNetworkPanel.class, "ChemicalSpaceNetworkPanel.descriptorsPanel.border.title"))); // NOI18N
        descriptorsPanel.setMinimumSize(new java.awt.Dimension(442, 180));
        descriptorsPanel.setPreferredSize(new java.awt.Dimension(442, 180));
        descriptorsPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(descriptorsPanel, gridBagConstraints);

        southPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(southPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getEditPanel(Algorithm algo) {
        this.csnAlgo = (ChemicalSpaceNetwork) algo;
        thresholdPanel.setup(csnAlgo);
        setMolecularDescriptors(pc.getAttributesModel());
        return this;
    }

    private void setMolecularDescriptors(AttributesModel attrModel) {
        descriptorsPanel.removeAll();
        DescriptorSelectionPanel selectionPanel = new DescriptorSelectionPanel(attrModel);
        final Set<String> keys = csnAlgo.getSelectedKeys();
        selectionPanel.setSelectedDescriptorKeys(keys);
        selectionPanel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                TableModel model = (TableModel) e.getSource();
                for (int row = 0; row < model.getRowCount(); row++) {
                    if ((boolean) model.getValueAt(row, 0)) {
                        keys.add((String) model.getValueAt(row, 1));
                    } else {
                        keys.remove((String) model.getValueAt(row, 1));
                    }
                }
            }
        });
        descriptorsPanel.add(selectionPanel, BorderLayout.CENTER);
        descriptorsPanel.revalidate();
        descriptorsPanel.repaint();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel descriptorsPanel;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void resultChanged(LookupEvent le) {
        if (le.getSource().equals(peptideLkpResult)){
            Collection<? extends AttributesModel> attrModels = peptideLkpResult.allInstances();
             if (!attrModels.isEmpty()){
                 csnAlgo.getSelectedKeys().clear();
                 setMolecularDescriptors(attrModels.iterator().next());
             }
        }
    }
}
