/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.network.impl;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.bapedis.core.model.AttributesModel;
import org.bapedis.core.services.ProjectManager;
import org.bapedis.core.spi.algo.Algorithm;
import org.bapedis.core.spi.algo.AlgorithmSetupUI;
import org.bapedis.core.ui.components.DescriptorSelectionPanel;
import org.openide.util.Lookup;

/**
 *
 * @author loge
 */
public class ChemicalSpaceNetworkPanel extends javax.swing.JPanel implements AlgorithmSetupUI {

    /**
     * Creates new form ChemicalSpaceNetworkPanel
     */
    protected ChemicalSpaceNetwork csnAlgo;
    protected final ThresholdRangePanel thresholdPanel;
    

    public ChemicalSpaceNetworkPanel() {
        initComponents();
        thresholdPanel = new ThresholdRangePanel();
        southPanel.add(thresholdPanel, BorderLayout.CENTER);        
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        descriptorsPanel = new javax.swing.JPanel();
        southPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        descriptorsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(ChemicalSpaceNetworkPanel.class, "ChemicalSpaceNetworkPanel.descriptorsPanel.border.title"))); // NOI18N
        descriptorsPanel.setMinimumSize(new java.awt.Dimension(442, 180));
        descriptorsPanel.setPreferredSize(new java.awt.Dimension(442, 180));
        descriptorsPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(descriptorsPanel, gridBagConstraints);

        southPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(southPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getEditPanel(Algorithm algo) {
        this.csnAlgo = (ChemicalSpaceNetwork) algo;
        AttributesModel attrModel = Lookup.getDefault().lookup(ProjectManager.class).getAttributesModel();
        descriptorsPanel.add(new DescriptorSelectionPanel(attrModel), BorderLayout.CENTER);
        thresholdPanel.setup(csnAlgo);
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel descriptorsPanel;
    private javax.swing.JPanel southPanel;
    // End of variables declaration//GEN-END:variables
}
