/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.io.impl;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.bapedis.core.ui.components.ValidationSupportUI;

/**
 *
 * @author Loge
 */
public class FASTAImporterUI extends javax.swing.JPanel implements ValidationSupportUI {

    private JFileChooser chooser;
    protected static File parentDirectory;
    protected File selectedFile;
    protected boolean validState;
    protected final PropertyChangeSupport changeSupport;

    /**
     * Creates new form FASTAImporterUI
     */
    public FASTAImporterUI() {
        initComponents();

        chooser = new JFileChooser();
        chooser.setCurrentDirectory(new java.io.File("."));
        chooser.setDialogTitle("Open FASTA file");
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter fileFilter = new FileNameExtensionFilter("FASTA format (*.fasta)", "fasta");
        chooser.addChoosableFileFilter(fileFilter);
        chooser.setFileFilter(fileFilter);

        validState = false;
        changeSupport = new PropertyChangeSupport(this);

        jTF_file.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateValidState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateValidState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });

        jTF_workspace.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateValidState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateValidState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
            }
        });
    }

    private void updateValidState() {
        boolean oldValidState = validState;
        if (jTF_file.getText().isEmpty() ||
            jTF_workspace.getText().isEmpty()) {
            validState = false;
        }else{
            validState = true;
        }
        changeSupport.firePropertyChange(VALID_STATE, oldValidState, validState);
    }

    public File getSelectedFile() {
        return selectedFile;
    }

    public String getLabelOfNodes() {
        return jTF_workspace.getText();
    }

    public String getWorkspaceName() {
        return jTF_workspace.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTF_file = new javax.swing.JTextField();
        jBtBrowse = new javax.swing.JButton();
        fileLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTF_workspace = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(429, 165));
        setPreferredSize(new java.awt.Dimension(430, 200));
        setLayout(new java.awt.GridBagLayout());

        jTF_file.setEditable(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(jTF_file, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jBtBrowse, org.openide.util.NbBundle.getMessage(FASTAImporterUI.class, "FASTAImporterUI.jBtBrowse.text")); // NOI18N
        jBtBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jBtBrowse, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(fileLabel, org.openide.util.NbBundle.getMessage(FASTAImporterUI.class, "FASTAImporterUI.fileLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(fileLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(FASTAImporterUI.class, "FASTAImporterUI.jLabel2.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 0);
        add(jLabel2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(jTF_workspace, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtBrowseActionPerformed
        if (parentDirectory != null) {
            chooser.setCurrentDirectory(parentDirectory);
        }
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File inputFile = chooser.getSelectedFile();
            jTF_file.setText(inputFile.getAbsolutePath());
            String name = inputFile.getName();
            if (jTF_workspace.getText().isEmpty()) {
                jTF_workspace.setText(name.replaceFirst("[.][^.]+$", ""));
            }
            boolean oldValidState = validState;
            validState = true;
            changeSupport.firePropertyChange(VALID_STATE, oldValidState, validState);
        }
    }//GEN-LAST:event_jBtBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel fileLabel;
    private javax.swing.JButton jBtBrowse;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTF_file;
    private javax.swing.JTextField jTF_workspace;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean isValidState() {
        if (jTF_file.getText().isEmpty()) {
            return false;
        }
        if (jTF_workspace.getText().isEmpty()) {
            return false;
        }
        return validState;
    }

    @Override
    public void saveSettings() {
        selectedFile = new File(jTF_file.getText());
        parentDirectory = selectedFile.getParentFile();
    }

    @Override
    public void cancelSettings() {
        selectedFile = null;
    }

    @Override
    public void addValidStateListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    @Override
    public void removeValidStateListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }
}
