/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.ui;

import java.awt.BorderLayout;
import javax.swing.DefaultComboBoxModel;
import org.bapedis.core.model.AnnotationType;
import org.bapedis.core.model.LibraryNode;
import org.openide.explorer.ExplorerManager;
import org.openide.explorer.view.BeanTreeView;
import org.openide.util.NbBundle;

/**
 *
 * @author cicese
 */
public class LibraryPanel extends javax.swing.JPanel implements ExplorerManager.Provider {

    protected final ExplorerManager explorerMgr;

    /**
     * Creates new form LibraryPanel
     */
    public LibraryPanel() {
        initComponents();
        explorerMgr = new ExplorerManager();

        BeanTreeView view = new BeanTreeView();
        view.setRootVisible(false);
        
        centerPanel.add(view, BorderLayout.CENTER);

        explorerMgr.setRootContext(new LibraryNode());
        
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        String NO_SELECTION = NbBundle.getMessage(LibraryPanel.class, "LibraryPanel.choose.text");
        comboBoxModel.addElement(NO_SELECTION);
        comboBoxModel.setSelectedItem(NO_SELECTION);
        
        for (AnnotationType aType : AnnotationType.values()){
            comboBoxModel.addElement(aType);
        }
        comboBox.setModel(comboBoxModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topPanel = new javax.swing.JPanel();
        comboBox = new javax.swing.JComboBox<>();
        centerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.GridBagLayout());

        topPanel.setPreferredSize(new java.awt.Dimension(400, 30));
        topPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select", " " }));
        topPanel.add(comboBox);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 2;
        add(topPanel, gridBagConstraints);

        centerPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(centerPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JPanel topPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public ExplorerManager getExplorerManager() {
        return explorerMgr;
    }

}
