/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.db.ui;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;
import org.gephi.appearance.spi.TransformerCategory;
import org.gephi.desktop.appearance.AppearanceToolbar;
import org.gephi.desktop.appearance.AppearanceUIController;
import org.gephi.desktop.appearance.AppearanceUIModel;
import org.gephi.ui.utils.UIUtils;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

/**
 *
 * @author Home
 */
public class ExtendedBar extends javax.swing.JPanel implements ActionListener {

    private transient final AppearanceToolbar toolbar;
    private transient final AppearanceUIController controller;
    private transient final ExtendedPanel extendedPanel;
    private transient final DialogDescriptor dd;
    private transient AppearanceUIModel model;

    /**
     * Creates new form ExtendedBar
     */
    public ExtendedBar() {
        controller = Lookup.getDefault().lookup(AppearanceUIController.class);
        model = controller.getModel();
        toolbar = new AppearanceToolbar(controller);
        initComponents();
        if (UIUtils.isAquaLookAndFeel()) {
            setBackground(UIManager.getColor("NbExplorerView.background"));
        }

        AppearanceToolbar.CategoryToolbar ctb = toolbar.getCategoryToolbar();
        ctb.addActionListener(this);
        add(ctb, BorderLayout.CENTER);
        extendedPanel = new ExtendedPanel(controller, toolbar);
        dd = new DialogDescriptor(extendedPanel, "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void actionPerformed(ActionEvent e) {
        TransformerCategory c = model.getSelectedCategory();
        String elementLabel = NbBundle.getMessage(ExtendedBar.class, "ExtendedBar." + model.getSelectedElementClass() + ".label");
        dd.setTitle(elementLabel + ": " + c.getDisplayName());
        if (DialogDisplayer.getDefault().notify(dd).equals(NotifyDescriptor.OK_OPTION)) {
            System.out.println("ok - extended panel");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
