/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.db.ui;

import java.awt.BorderLayout;
import java.beans.PropertyChangeEvent;
import javax.swing.UIManager;
import org.gephi.desktop.appearance.AppearanceToolbar;
import org.gephi.desktop.appearance.AppearanceUIController;
import org.gephi.desktop.appearance.AppearanceUIModel;
import org.gephi.desktop.appearance.AppearanceUIModelEvent;
import org.gephi.desktop.appearance.AppearanceUIModelListener;
import org.gephi.ui.utils.UIUtils;
import org.openide.DialogDescriptor;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.Lookup;

/**
 *
 * @author Home
 */
public class ExtendedBar extends javax.swing.JPanel implements AppearanceUIModelListener {

    private transient final AppearanceToolbar toolbar;
    private transient final AppearanceUIController controller;
    private transient AppearanceUIModel model;
    private transient ExtendedPanel extendedPanel;

    /**
     * Creates new form ExtendedBar
     */
    public ExtendedBar() {
        controller = Lookup.getDefault().lookup(AppearanceUIController.class);
        model = controller.getModel();
        controller.addPropertyChangeListener(this);
        toolbar = new AppearanceToolbar(controller);
        initComponents();
        if (UIUtils.isAquaLookAndFeel()) {
            setBackground(UIManager.getColor("NbExplorerView.background"));
        }

        add(toolbar.getCategoryToolbar(), BorderLayout.CENTER);
        extendedPanel = new ExtendedPanel(toolbar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getPropertyName().equals(AppearanceUIModelEvent.SELECTED_CATEGORY)) {
            DialogDescriptor dd = new DialogDescriptor(extendedPanel, "title");
            if (DialogDisplayer.getDefault().notify(dd).equals(NotifyDescriptor.OK_OPTION)) {
                System.out.println("ok - extended panel");
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
