/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.chemspace.wizard;

import java.awt.BorderLayout;
import javax.swing.JPanel;
import org.bapedis.chemspace.model.WizardOptionModel;
import org.openide.util.NbBundle;

public final class VisualFeatureExtraction extends JPanel {

    public static final String MD_OPTION = "md_option";
    private final JPanel settingPanel;
    private MolecularDescriptorOption optionModel;

    public VisualFeatureExtraction(MolecularDescriptorOption optionModel, JPanel settingPanel) {
        initComponents();

        this.optionModel = optionModel;
        this.settingPanel = settingPanel;

        bottomPanel.add(settingPanel, BorderLayout.CENTER);

        switch (optionModel) {
            case AVAILABLE:
                jOption1.setSelected(true);
                break;
            case NEW:
                jOption2.setSelected(true);
                break;
        }
        settingPanel.setEnabled(optionModel == MolecularDescriptorOption.NEW);
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(VisualFeatureExtraction.class, "FeatureExtraction.name");
    }

    public WizardOptionModel.MolecularDescriptorOption getSelectedOption() {
        if (jOption2.isSelected()) {
            return WizardOptionModel.MolecularDescriptorOption.NEW;
        }
        if (jOption1.isSelected()) {
            return WizardOptionModel.MolecularDescriptorOption.AVAILABLE;
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jQuestionLabel = new javax.swing.JLabel();
        jOption2 = new javax.swing.JRadioButton();
        jOption1 = new javax.swing.JRadioButton();
        bottomPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(460, 400));
        setPreferredSize(new java.awt.Dimension(500, 460));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jQuestionLabel, org.openide.util.NbBundle.getMessage(VisualFeatureExtraction.class, "VisualFeatureExtraction.jQuestionLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jQuestionLabel, gridBagConstraints);

        buttonGroup1.add(jOption2);
        org.openide.awt.Mnemonics.setLocalizedText(jOption2, org.openide.util.NbBundle.getMessage(VisualFeatureExtraction.class, "VisualFeatureExtraction.jOption2.text")); // NOI18N
        jOption2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOption2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jOption2, gridBagConstraints);

        buttonGroup1.add(jOption1);
        org.openide.awt.Mnemonics.setLocalizedText(jOption1, org.openide.util.NbBundle.getMessage(VisualFeatureExtraction.class, "VisualFeatureExtraction.jOption1.text")); // NOI18N
        jOption1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jOption1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jOption1, gridBagConstraints);

        bottomPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bottomPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(bottomPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jOption2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOption2ActionPerformed
        MolecularDescriptorOption oldOption = optionModel;
        optionModel = MolecularDescriptorOption.NEW;
        settingPanel.setEnabled(true);
        firePropertyChange(MD_OPTION, oldOption, optionModel);
    }//GEN-LAST:event_jOption2ActionPerformed

    private void jOption1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jOption1ActionPerformed
        MolecularDescriptorOption oldOption = optionModel;
        optionModel = MolecularDescriptorOption.AVAILABLE;
        settingPanel.setEnabled(false);
        firePropertyChange(MD_OPTION, oldOption, optionModel);
    }//GEN-LAST:event_jOption1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jOption1;
    private javax.swing.JRadioButton jOption2;
    private javax.swing.JLabel jQuestionLabel;
    // End of variables declaration//GEN-END:variables

}
