/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.chemspace.wizard;

import java.awt.Component;
import java.util.Collection;
import java.util.HashMap;
import javax.swing.Icon;
import javax.swing.JPanel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.openide.util.ImageUtilities;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;
import org.bapedis.chemspace.similarity.AbstractSimCoefficient;
import org.bapedis.core.model.AlgorithmNode;
import org.bapedis.core.spi.alg.AlgorithmFactory;
import org.bapedis.core.spi.alg.SimilarityTag;
import org.bapedis.core.ui.components.PropertySheetPanel;
import org.openide.nodes.Node;

public final class VisualSimCoefficient extends JPanel {

    public static final String NETWORK_FACTORY = "network_factory";
    private final DefaultMutableTreeNode treeNode;
    private AbstractSimCoefficient simCoefficient;
    private final PropertySheetPanel propSheetPanel;
    private final HashMap<String, AbstractSimCoefficient> map;

    public VisualSimCoefficient() {
        initComponents();
        treeNode = new DefaultMutableTreeNode(NbBundle.getMessage(VisualSimCoefficient.class, "SimCoefficient.root.name"), true);
        populateJTree();
        jTree1.setModel(new DefaultTreeModel(treeNode));
        jTree1.setRootVisible(true);
        jTree1.setCellRenderer(new SimilarityFactoryNodeRenderer());
        map = new HashMap<>();
        propSheetPanel = new PropertySheetPanel();
        propSheetPanel.setPreferredSize(jScrollPane2.getPreferredSize());
    }

    public AbstractSimCoefficient getSimilarityCoefficient() {
        return simCoefficient;
    }

    public void setSimilarityCoefficient(AbstractSimCoefficient coefficient) {
        this.simCoefficient = coefficient;
        AlgorithmFactory factory = coefficient.getFactory();
        map.put(factory.getName(), coefficient);
        SimilarityFactoryTreeNode factoryNode;
        for (int i = 0; i < treeNode.getChildCount(); i++) {
            factoryNode = (SimilarityFactoryTreeNode) treeNode.getChildAt(i);
            if (factoryNode.getFactory().getName().equals(factory.getName())) {
                jTree1.setSelectionPath(new TreePath(factoryNode.getPath()));
            }
        }
    }

    private void populateJTree() {
        Collection<? extends AlgorithmFactory> factories = Lookup.getDefault().lookupAll(AlgorithmFactory.class);
        for (AlgorithmFactory factory : factories) {
            if (factory instanceof SimilarityTag) {
                treeNode.add(new SimilarityFactoryTreeNode(factory));
            }
        }
    }

    @Override
    public String getName() {
        return NbBundle.getMessage(VisualSimCoefficient.class, "SimCoefficient.name");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jInfoLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDescLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(460, 400));
        setPreferredSize(new java.awt.Dimension(680, 460));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jInfoLabel, org.openide.util.NbBundle.getMessage(VisualSimCoefficient.class, "VisualSimCoefficient.jInfoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jInfoLabel, gridBagConstraints);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(220, 322));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(220, 322));

        jTree1.setRootVisible(false);
        jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTree1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTree1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jScrollPane1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jScrollPane2, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jDescLabel, org.openide.util.NbBundle.getMessage(VisualSimCoefficient.class, "VisualSimCoefficient.jDescLabel.text")); // NOI18N
        jDescLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jDescLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jDescLabel.setMinimumSize(new java.awt.Dimension(4, 87));
        jDescLabel.setPreferredSize(new java.awt.Dimension(4, 87));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jDescLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTree1ValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTree1ValueChanged
        TreePath newPath = evt.getNewLeadSelectionPath();
        AlgorithmFactory factory = null;
        if (newPath != null && newPath.getLastPathComponent() instanceof SimilarityFactoryTreeNode) {
            SimilarityFactoryTreeNode newNode = (SimilarityFactoryTreeNode) newPath.getLastPathComponent();
            factory = newNode.getFactory();
            jDescLabel.setText(NbBundle.getMessage(VisualSimCoefficient.class, "VisualSimCoefficient.jDescLabel.text", factory.getName(), factory.getDescription()));
            if (!map.containsKey(factory.getName())) {
                simCoefficient = (AbstractSimCoefficient)factory.createAlgorithm();
                map.put(factory.getName(), simCoefficient);
            } else {
                simCoefficient = map.get(factory.getName());
            }
            if (factory.getSetupUI() != null) {
                JPanel panel = factory.getSetupUI().getSettingPanel(simCoefficient);
                jScrollPane2.setViewportView(panel);
                jDescLabel.setVisible(true);
            } else if (simCoefficient.getProperties() != null) {
                propSheetPanel.getPropertySheet().setNodes(new Node[]{new AlgorithmNode(simCoefficient)});
                jScrollPane2.setViewportView(propSheetPanel);
                jDescLabel.setVisible(false);
            }
            else {
                jScrollPane2.setViewportView(null);
                jDescLabel.setVisible(true);
            }

        } else {
            simCoefficient = null;
            jDescLabel.setText("");
            jScrollPane2.setViewportView(null);
            jDescLabel.setVisible(false);
        }
        firePropertyChange(NETWORK_FACTORY, null, factory);
    }//GEN-LAST:event_jTree1ValueChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jDescLabel;
    private javax.swing.JLabel jInfoLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    private static class SimilarityFactoryTreeNode extends DefaultMutableTreeNode {

        public SimilarityFactoryTreeNode(AlgorithmFactory factory) {
            super(factory, false);
        }

        public AlgorithmFactory getFactory() {
            return (AlgorithmFactory) userObject;
        }

        @Override
        public String toString() {
            return getFactory().getName();
        }

    }

    private static class SimilarityFactoryNodeRenderer extends DefaultTreeCellRenderer {

        Icon icon;

        public SimilarityFactoryNodeRenderer() {
            icon = ImageUtilities.loadImageIcon("org/bapedis/chemspace/resources/network.png", false);
        }

        @Override
        public Component getTreeCellRendererComponent(
                JTree tree,
                Object value,
                boolean sel,
                boolean expanded,
                boolean leaf,
                int row,
                boolean hasFocus) {

            super.getTreeCellRendererComponent(
                    tree, value, sel,
                    expanded, leaf, row,
                    hasFocus);
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) value;
            if (!(node instanceof SimilarityFactoryTreeNode)) {
                // Root node
                setIcon(icon);
            }
            return this;
        }
    }

}
