/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.ui.components;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.SwingConstants;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.TableModel;
import org.bapedis.core.model.AttributesModel;
import org.bapedis.core.model.MolecularDescriptor;
import org.bapedis.core.model.Workspace;
import org.bapedis.core.spi.algo.impl.DeleteDescriptorAlgo;
import org.bapedis.core.spi.algo.impl.DeleteDescriptorFactory;
import org.bapedis.core.task.AlgorithmExecutor;
import static org.bapedis.core.ui.components.FeatureFilterPanel.executor;
import org.jdesktop.swingx.JXBusyLabel;
import org.openide.DialogDisplayer;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

/**
 * @author loge
 */
public class DeleteMDPanel extends javax.swing.JPanel implements PropertyChangeListener {

    protected static final AlgorithmExecutor executor = Lookup.getDefault().lookup(AlgorithmExecutor.class);
    protected final Workspace workspace;
    protected DeleteDescriptorAlgo algo;
    protected final DescriptorSelectionPanel selectionPanel;
    protected final JXBusyLabel busyLabel;

    public DeleteMDPanel(Workspace workspace) {
        initComponents();
        
        this.workspace = workspace;
        
        algo = workspace.getLookup().lookup(DeleteDescriptorAlgo.class);
        if (algo == null){
            algo = (DeleteDescriptorAlgo) new DeleteDescriptorFactory().createAlgorithm();
            workspace.add(algo);
        }
        
        AttributesModel attrModel = workspace.getLookup().lookup(AttributesModel.class);        
        selectionPanel = new DescriptorSelectionPanel(attrModel, Color.RED);
        selectionPanel.removeDescriptorRow(MolecularDescriptor.DEFAULT_CATEGORY);
        selectionPanel.setSelectedDescriptorKeys(algo.getDescriptorKeys());

        centerPanel.add(selectionPanel, BorderLayout.CENTER);

        busyLabel = new JXBusyLabel(new Dimension(20, 20));
        busyLabel.setText(NbBundle.getMessage(DeleteMDPanel.class, "DeleteMDPanel.deleting.text"));
        busyLabel.setHorizontalAlignment(SwingConstants.CENTER);
        boolean running = algo.isRunning();
        busyLabel.setBusy(running);
        busyLabel.setVisible(running);
        rightPanel.add(busyLabel);

        deleteButton.setEnabled(selectionPanel.getSelectedDescriptorKeys().size()>0);

        selectionPanel.addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                TableModel model = (TableModel) e.getSource();
                boolean flag = false;
                for (int row = 0; row < model.getRowCount(); row++) {
                    if ((boolean) model.getValueAt(row, 0)) {
                        flag = true;
                        algo.includeAlgorithm((String)model.getValueAt(row, 1));
                    } else{
                        algo.excludeAlgorithm((String)model.getValueAt(row, 1));
                    }
                }
                deleteButton.setEnabled(flag);
            }
        });
        
        addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                algo.addPropertyChangeListener(DeleteMDPanel.this);
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
                algo.removePropertyChangeListener(DeleteMDPanel.this);
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rightPanel = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(440, 380));
        setPreferredSize(new java.awt.Dimension(540, 380));
        setLayout(new java.awt.GridBagLayout());

        rightPanel.setMaximumSize(new java.awt.Dimension(110, 58));
        rightPanel.setMinimumSize(new java.awt.Dimension(110, 58));
        rightPanel.setPreferredSize(new java.awt.Dimension(110, 58));
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.Y_AXIS));

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/core/resources/delete.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(deleteButton, org.openide.util.NbBundle.getMessage(DeleteMDPanel.class, "DeleteMDPanel.deleteButton.text")); // NOI18N
        deleteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteButton.setMaximumSize(new java.awt.Dimension(99, 29));
        deleteButton.setMinimumSize(new java.awt.Dimension(99, 29));
        deleteButton.setPreferredSize(new java.awt.Dimension(99, 29));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        rightPanel.add(deleteButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        add(rightPanel, gridBagConstraints);

        centerPanel.setMinimumSize(new java.awt.Dimension(275, 10));
        centerPanel.setPreferredSize(new java.awt.Dimension(275, 100));
        centerPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(centerPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if (workspace.isBusy()) {
            DialogDisplayer.getDefault().notify(workspace.getBusyNotifyDescriptor());
        } else {
            executor.execute(algo);          
        }
    }//GEN-LAST:event_deleteButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getSource().equals(algo) && evt.getPropertyName().equals(DeleteDescriptorAlgo.RUNNING)){
            boolean running = algo.isRunning();
            busyLabel.setBusy(running);
            busyLabel.setVisible(running);            
        }
    }
}
