/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.ui.components;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.SwingWorker;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.AbstractTableModel;
import org.bapedis.core.model.AttributesModel;
import org.bapedis.core.model.PeptideAttribute;
import org.jdesktop.swingx.JXBusyLabel;
import org.jdesktop.swingx.JXTable;
import org.jdesktop.swingx.decorator.HighlighterFactory;
import org.openide.util.Exceptions;
import org.openide.util.NbBundle;

/**
 *
 * @author loge
 */
public class DescriptorRemovalPanel extends javax.swing.JPanel {

    protected final DescriptorSelectionPanel selectionPanel;
    protected final JXBusyLabel busyLabel;
    protected final AttributesModel attrModel;

    public DescriptorRemovalPanel(AttributesModel attrModel) {
        initComponents();
        this.attrModel = attrModel;
        
        selectionPanel = new DescriptorSelectionPanel(attrModel);
        centerPanel.add(selectionPanel, BorderLayout.CENTER);

        busyLabel = new JXBusyLabel(new Dimension(20, 20));
        busyLabel.setText(NbBundle.getMessage(DescriptorRemovalPanel.class, "DescriptorRemovalPanel.deleting.text"));
        busyLabel.setHorizontalAlignment(SwingConstants.CENTER);
        busyLabel.setBusy(false);
        busyLabel.setVisible(false);
        rightPanel.add(busyLabel);

        deleteButton.setEnabled(false);
        deleteAllButton.setEnabled(false);
    }


    private void delete() {
//        final int[] selectedRows = table.getSelectedRows();
//        for (int i = 0; i < selectedRows.length; i++) {
//            selectedRows[i] = table.convertRowIndexToModel(selectedRows[i]);
//        }
//        SwingWorker sw = new SwingWorker() {
//            @Override
//            protected Object doInBackground() throws Exception {
//                String key;
//                List<PeptideAttribute> list;
//                for (int i = 0; i < selectedRows.length; i++) {
//                    key = (String) table.getModel().getValueAt(selectedRows[i], 0);
//                    list = map.get(key);
//                    for (PeptideAttribute attribute : list) {
//                        attrModel.deleteAttribute(attribute);
//                    }
//                    map.remove(key);
//                }
//                return null;
//            }
//
//            @Override
//            protected void done() {
//                try {
//                    get();
//                    ((MyTableModel) table.getModel()).removeRows(selectedRows);
//                } catch (InterruptedException | ExecutionException ex) {
//                    Exceptions.printStackTrace(ex);
//                } finally {
//                    busyLabel.setBusy(false);
//                    busyLabel.setVisible(false);
//                    deleteAllButton.setEnabled(table.getRowCount() > 0);
//                }
//            }
//        };
//        busyLabel.setBusy(true);
//        busyLabel.setVisible(true);
//        deleteButton.setEnabled(false);
//        deleteAllButton.setEnabled(false);
//        sw.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        rightPanel = new javax.swing.JPanel();
        deleteButton = new javax.swing.JButton();
        deleteAllButton = new javax.swing.JButton();
        centerPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(440, 380));
        setPreferredSize(new java.awt.Dimension(540, 380));
        setLayout(new java.awt.GridBagLayout());

        rightPanel.setMaximumSize(new java.awt.Dimension(110, 58));
        rightPanel.setMinimumSize(new java.awt.Dimension(110, 58));
        rightPanel.setPreferredSize(new java.awt.Dimension(110, 58));
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.Y_AXIS));

        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/core/resources/delete.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(deleteButton, org.openide.util.NbBundle.getMessage(DescriptorRemovalPanel.class, "DescriptorRemovalPanel.deleteButton.text")); // NOI18N
        deleteButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteButton.setMaximumSize(new java.awt.Dimension(99, 29));
        deleteButton.setMinimumSize(new java.awt.Dimension(99, 29));
        deleteButton.setPreferredSize(new java.awt.Dimension(99, 29));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        rightPanel.add(deleteButton);

        deleteAllButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/core/resources/delete.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(deleteAllButton, org.openide.util.NbBundle.getMessage(DescriptorRemovalPanel.class, "DescriptorRemovalPanel.deleteAllButton.text")); // NOI18N
        deleteAllButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deleteAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAllButtonActionPerformed(evt);
            }
        });
        rightPanel.add(deleteAllButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(25, 5, 0, 5);
        add(rightPanel, gridBagConstraints);

        centerPanel.setMinimumSize(new java.awt.Dimension(275, 10));
        centerPanel.setPreferredSize(new java.awt.Dimension(275, 100));
        centerPanel.setLayout(new java.awt.BorderLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 2, 0);
        add(centerPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        delete();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void deleteAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAllButtonActionPerformed
//        if (table.getRowCount() > 0) {
//            table.setRowSelectionInterval(0, table.getRowCount() - 1);
//            delete();
//        }
    }//GEN-LAST:event_deleteAllButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JButton deleteAllButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JPanel rightPanel;
    // End of variables declaration//GEN-END:variables
}
