/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.ui.components;

import org.bapedis.core.spi.alg.impl.FeatureSEFilteringPanel;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.SwingConstants;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import org.bapedis.core.model.Workspace;
import org.bapedis.core.spi.alg.impl.FeatureSEFiltering;
import org.bapedis.core.spi.alg.impl.FeatureSEFilteringFactory;
import org.jdesktop.swingx.JXBusyLabel;
import org.openide.DialogDescriptor;
import org.openide.util.NbBundle;

/**
 *
 * @author loge
 */
public class FeatureFilterPanel extends javax.swing.JPanel implements PropertyChangeListener {

    protected Workspace workspace;
    protected FeatureSEFiltering algo;
    protected final JXBusyLabel busyLabel;
    protected final FeatureSEFilteringPanel settingPanel;
    protected DialogDescriptor dd;

    /**
     * Creates new form FeatureFilterPanel
     *
     * @param workspace
     */
    public FeatureFilterPanel(Workspace workspace) {
        initComponents();

        this.workspace = workspace;

        algo = workspace.getLookup().lookup(FeatureSEFiltering.class);
        if (algo == null) {
            algo = (FeatureSEFiltering) new FeatureSEFilteringFactory().createAlgorithm();
            workspace.add(algo);
        }

        busyLabel = new JXBusyLabel(new Dimension(20, 20));
        busyLabel.setText(NbBundle.getMessage(FeatureFilterPanel.class, "FeatureFilterPanel.filtering.text"));
        busyLabel.setHorizontalAlignment(SwingConstants.CENTER);
        boolean running = algo.isRunning();
        busyLabel.setBusy(running);
        busyLabel.setVisible(running);
        add(busyLabel, BorderLayout.PAGE_START);

        addAncestorListener(new AncestorListener() {
            @Override
            public void ancestorAdded(AncestorEvent event) {
                algo.addPropertyChangeListener(FeatureFilterPanel.this);
                if (dd != null) {
                    dd.setValid(!algo.isRunning());
                }
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
                algo.removePropertyChangeListener(FeatureFilterPanel.this);
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });

        settingPanel = (FeatureSEFilteringPanel) algo.getFactory().getSetupUI().getSettingPanel(algo);
        centerPanel.add(settingPanel, BorderLayout.CENTER);
    }

    public FeatureSEFiltering getAlgorithm() {
        return algo;
    }

    public DialogDescriptor getDialogDescriptor() {
        return dd;
    }

    public void setDialogDescriptor(DialogDescriptor dd) {
        this.dd = dd;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(440, 380));
        setPreferredSize(new java.awt.Dimension(540, 380));
        setLayout(new java.awt.BorderLayout());

        centerPanel.setPreferredSize(new java.awt.Dimension(259, 130));
        centerPanel.setLayout(new java.awt.BorderLayout());
        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void propertyChange(PropertyChangeEvent evt) {
        if (evt.getSource().equals(algo) && evt.getPropertyName().equals(FeatureSEFiltering.RUNNING)) {
            boolean running = algo.isRunning();
            busyLabel.setBusy(running);
            busyLabel.setVisible(running);
            if (dd != null) {
                dd.setValid(!running);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    // End of variables declaration//GEN-END:variables
}
