/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.core.ui.components;

import java.util.Hashtable;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import org.bapedis.core.model.SequenceAlignmentModel;
import org.openide.util.NbBundle;

/**
 *
 * @author loge
 */
public class SequenceAlignmentPanel extends javax.swing.JPanel {

    private final SequenceAlignmentModel model;

    /**
     * Creates new form SequenceAlignmentPanel
     *
     * @param model
     */
    public SequenceAlignmentPanel(SequenceAlignmentModel model) {
        initComponents();

        this.model = model;

        DefaultComboBoxModel<String> comboBoxModel = new DefaultComboBoxModel();
        for (String s : SequenceAlignmentModel.ALIGNMENT_TYPE) {
            comboBoxModel.addElement(s);
        }
        jATComboBox.setModel(comboBoxModel);
        jATComboBox.setSelectedIndex(model.getAlignmentTypeIndex());
        setInfoLabel();

        comboBoxModel = new DefaultComboBoxModel<>();
        for (String s : SequenceAlignmentModel.SUBSTITUTION_MATRIX) {
            comboBoxModel.addElement(s);
        }
        jSMComboBox.setModel(comboBoxModel);
        jSMComboBox.setSelectedIndex(model.getSubstitutionMatrixIndex());

        jPIDSlider.setMinimum(SequenceAlignmentModel.PID_MIN);
        jPIDSlider.setMaximum(SequenceAlignmentModel.PID_MAX);
        jPIDSlider.setMajorTickSpacing(SequenceAlignmentModel.PID_MAJORTICKSPACING);
        jPIDSlider.setMinorTickSpacing(SequenceAlignmentModel.PID_MINORTICKSPACING);

        //Label table
        Hashtable<Integer, JLabel> labelTable = new Hashtable<>();
        labelTable.put(SequenceAlignmentModel.PID_REFS[0], new JLabel(NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.pidSlider.veryLow")));
        labelTable.put(SequenceAlignmentModel.PID_REFS[1], new JLabel(NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.pidSlider.low")));
        labelTable.put(SequenceAlignmentModel.PID_REFS[2], new JLabel(NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.pidSlider.middle")));
        labelTable.put(SequenceAlignmentModel.PID_REFS[3], new JLabel(NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.pidSlider.high")));

        jPIDSlider.setLabelTable(labelTable);
        jPIDLabel.setText(model.getPercentIdentity() + "%");
        jPIDSlider.setValue(model.getPercentIdentity());

//        pidRichTooltip = new RichTooltip();
//        pidRichTooltip.setTitle(NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.pidInfo.title"));
//        pidRichTooltip.addDescriptionSection(NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.pidInfo1.text"));
//        pidRichTooltip.addDescriptionSection(NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.pidInfo2.text"));
    }

    public void showPercentangeIdSlider(boolean flag){
        jToolBar1.setVisible(flag);
        jPIDInfoLabel.setVisible(flag);
        jPIDLabel.setVisible(flag);
    }
    
    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled); //To change body of generated methods, choose Tools | Templates.

        jResetButton.setEnabled(enabled);
        jATLabel.setEnabled(enabled);
        jATComboBox.setEnabled(enabled);
        jSMLabel.setEnabled(enabled);
        jSMComboBox.setEnabled(enabled);
        jPIDInfoLabel.setEnabled(enabled);
        jPIDLabel.setEnabled(enabled);
        jLessButton.setEnabled(enabled);
        jPIDSlider.setEnabled(enabled);
        jMoreButton.setEnabled(enabled);
    }

    private void setInfoLabel() {
        switch (model.getAlignerType()) {
            case LOCAL:
                jPIDInfoLabel.setToolTipText("Identities * 100 / Length of shorter sequence");
                break;
            case GLOBAL:
                jPIDInfoLabel.setToolTipText("Identities * 100 / Columns");
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jATLabel = new javax.swing.JLabel();
        jATComboBox = new javax.swing.JComboBox();
        jSMLabel = new javax.swing.JLabel();
        jSMComboBox = new javax.swing.JComboBox();
        jPIDInfoLabel = new javax.swing.JLabel();
        jPIDLabel = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        jLessButton = new javax.swing.JButton();
        jPIDSlider = new javax.swing.JSlider();
        jMoreButton = new javax.swing.JButton();
        jextLabel = new javax.swing.JLabel();
        jResetButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(440, 224));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jATLabel, org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jATLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(jATLabel, gridBagConstraints);

        jATComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jATComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(jATComboBox, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jSMLabel, org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jSMLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        add(jSMLabel, gridBagConstraints);

        jSMComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSMComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        add(jSMComboBox, gridBagConstraints);

        jPIDInfoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/core/resources/info.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jPIDInfoLabel, org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jPIDInfoLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        add(jPIDInfoLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jPIDLabel, org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jPIDLabel.text")); // NOI18N
        jPIDLabel.setPreferredSize(new java.awt.Dimension(23, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        add(jPIDLabel, gridBagConstraints);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setFocusable(false);
        jToolBar1.setPreferredSize(new java.awt.Dimension(420, 90));

        jLessButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/core/resources/less.png"))); // NOI18N
        jLessButton.setToolTipText(org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jLessButton.toolTipText")); // NOI18N
        jLessButton.setFocusable(false);
        jLessButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLessButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jLessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLessButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(jLessButton);

        jPIDSlider.setMajorTickSpacing(10);
        jPIDSlider.setMinimum(30);
        jPIDSlider.setMinorTickSpacing(5);
        jPIDSlider.setPaintLabels(true);
        jPIDSlider.setPaintTicks(true);
        jPIDSlider.setToolTipText(org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jPIDSlider.toolTipText")); // NOI18N
        jPIDSlider.setValue(70);
        jPIDSlider.setMinimumSize(new java.awt.Dimension(360, 80));
        jPIDSlider.setPreferredSize(new java.awt.Dimension(360, 80));
        jPIDSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jPIDSliderStateChanged(evt);
            }
        });
        jToolBar1.add(jPIDSlider);

        jMoreButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/core/resources/more.png"))); // NOI18N
        jMoreButton.setToolTipText(org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jMoreButton.toolTipText")); // NOI18N
        jMoreButton.setFocusable(false);
        jMoreButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMoreButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMoreButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(jMoreButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(jToolBar1, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jextLabel, org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jextLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weighty = 1.0;
        add(jextLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(jResetButton, org.openide.util.NbBundle.getMessage(SequenceAlignmentPanel.class, "SequenceAlignmentPanel.jResetButton.text")); // NOI18N
        jResetButton.setMaximumSize(new java.awt.Dimension(145, 23));
        jResetButton.setMinimumSize(new java.awt.Dimension(145, 23));
        jResetButton.setPreferredSize(new java.awt.Dimension(145, 23));
        jResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jResetButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 0, 5);
        add(jResetButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jATComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jATComboBoxActionPerformed
        if (model.getAlignmentTypeIndex() != jATComboBox.getSelectedIndex()) {
            model.setAlignmentTypeIndex(jATComboBox.getSelectedIndex());
            setInfoLabel();
        }
    }//GEN-LAST:event_jATComboBoxActionPerformed

    private void jSMComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSMComboBoxActionPerformed
        if (model.getSubstitutionMatrixIndex() != jSMComboBox.getSelectedIndex()) {
            model.setSubstitutionMatrixIndex(jSMComboBox.getSelectedIndex());
        }
    }//GEN-LAST:event_jSMComboBoxActionPerformed

    private void jLessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLessButtonActionPerformed
        int pid = jPIDSlider.getValue();
        if (pid > jPIDSlider.getMinimum()) {
            jPIDSlider.setValue(pid - 1);
        }
    }//GEN-LAST:event_jLessButtonActionPerformed

    private void jPIDSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jPIDSliderStateChanged
        if (!jPIDSlider.getValueIsAdjusting() && model != null) {
            model.setPercentIdentity(jPIDSlider.getValue());
            jPIDLabel.setText(model.getPercentIdentity() + "%");
        }
    }//GEN-LAST:event_jPIDSliderStateChanged

    private void jMoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMoreButtonActionPerformed
        int pid = jPIDSlider.getValue();
        if (pid < jPIDSlider.getMaximum()) {
            jPIDSlider.setValue(pid + 1);
        }
    }//GEN-LAST:event_jMoreButtonActionPerformed

    private void jResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jResetButtonActionPerformed
        jATComboBox.setSelectedIndex(SequenceAlignmentModel.DEFAULT_ALIGNMENT_TYPE_INDEX);
        jSMComboBox.setSelectedIndex(SequenceAlignmentModel.DEFAULT_SUBSTITUTION_MATRIX_INDEX);
        jPIDSlider.setValue(SequenceAlignmentModel.DEFAULT_PID);
    }//GEN-LAST:event_jResetButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jATComboBox;
    private javax.swing.JLabel jATLabel;
    private javax.swing.JButton jLessButton;
    private javax.swing.JButton jMoreButton;
    private javax.swing.JLabel jPIDInfoLabel;
    private javax.swing.JLabel jPIDLabel;
    private javax.swing.JSlider jPIDSlider;
    private javax.swing.JButton jResetButton;
    private javax.swing.JComboBox jSMComboBox;
    private javax.swing.JLabel jSMLabel;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel jextLabel;
    // End of variables declaration//GEN-END:variables
}
