/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.chemspace.impl;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import org.bapedis.chemspace.model.EmbedderModel;
import org.bapedis.core.spi.alg.Algorithm;
import org.bapedis.core.spi.alg.AlgorithmFactory;
import org.bapedis.core.ui.components.AlgorithmFactoryItem;
import org.openide.util.NbBundle;
import org.bapedis.core.ui.components.PropertySheetPanel;

/**
 *
 * @author loge
 */
public abstract class BaseChemSpacePanel extends javax.swing.JPanel {

    protected AbstractEmbedder embedder;
    protected final String NO_SELECTION;

    /**
     * Creates new form BaseChemSpacePanel
     */
    public BaseChemSpacePanel(List<? extends AlgorithmFactory> factories) {
        initComponents();
        NO_SELECTION = NbBundle.getMessage(BaseChemSpacePanel.class, "BaseChemSpacePanel.choose.text");
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        comboBoxModel.addElement(NO_SELECTION);
        comboBoxModel.setSelectedItem(NO_SELECTION);

        for (AlgorithmFactory factory : factories) {
            AlgorithmFactoryItem item = new AlgorithmFactoryItem(factory);
            comboBoxModel.addElement(item);
        }

        algComboBox.setModel(comboBoxModel);
        setEnableState(false);
    }        

    protected void refreshAlgChooser(AbstractEmbedder embedder) {
        EmbedderModel embedderModel = embedder.getEmbedderModel();
        if (embedderModel != null) {
            DefaultComboBoxModel comboBoxModel = (DefaultComboBoxModel) algComboBox.getModel();
            Algorithm alg = embedderModel.getSelectedAlgorithm();
            AlgorithmFactory factory = (alg != null) ? alg.getFactory() : null;
            if (factory != null) {
                for (int i = 1; i < comboBoxModel.getSize(); i++) {
                    if (factory == ((AlgorithmFactoryItem) comboBoxModel.getElementAt(i)).getFactory()) {
                        comboBoxModel.setSelectedItem(comboBoxModel.getElementAt(i));
                    }
                }
            } else {
                comboBoxModel.setSelectedItem(NO_SELECTION);
            }
            setEnableState(!comboBoxModel.getSelectedItem().equals(NO_SELECTION));
        }

    }

    private void setEnableState(boolean enabled) {
        infoLabel.setEnabled(enabled);
        applyButton.setEnabled(enabled);
        propSheetPanel.setEnabled(enabled);
        scrollPane.setEnabled(enabled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        algComboBox = new javax.swing.JComboBox<>();
        infoLabel = new javax.swing.JLabel();
        applyButton = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        propSheetPanel = new PropertySheetPanel();

        setLayout(new java.awt.GridBagLayout());

        algComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                algComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 0, 0);
        add(algComboBox, gridBagConstraints);

        infoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/chemspace/resources/info.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(infoLabel, org.openide.util.NbBundle.getMessage(BaseChemSpacePanel.class, "BaseChemSpacePanel.infoLabel.text")); // NOI18N
        infoLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoLabelMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoLabelMouseEntered(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 0, 5);
        add(infoLabel, gridBagConstraints);

        applyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/bapedis/chemspace/resources/apply.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(applyButton, org.openide.util.NbBundle.getMessage(BaseChemSpacePanel.class, "BaseChemSpacePanel.applyButton.text")); // NOI18N
        applyButton.setToolTipText(org.openide.util.NbBundle.getMessage(BaseChemSpacePanel.class, "BaseChemSpacePanel.applyButton.toolTipText")); // NOI18N
        applyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(2, 5, 0, 0);
        add(applyButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(scrollPane, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(propSheetPanel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void algComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_algComboBoxActionPerformed
//        AlgorithmModel algoModel = pc.getAlgorithmModel();
//        if (algComboBox.getSelectedItem() instanceof AlgorithmFactoryItem) {
//            AlgorithmFactory factory = ((AlgorithmFactoryItem) algComboBox.getSelectedItem()).getFactory();
//            Workspace currentWs = pc.getCurrentWorkspace();
//            Collection<? extends Algorithm> savedAlgo = currentWs.getLookup().lookupAll(Algorithm.class);
//            Algorithm algorithm = null;
//            for (Algorithm algo : savedAlgo) {
//                if (algo.getFactory() == factory) {
//                    algorithm = algo;
//                    break;
//                }
//            }
//            boolean addToWS = false;
//            if (algorithm == null) {
//                algorithm = factory.createAlgorithm();
//                addToWS = true;
//            }
//
//            if (algorithm != null) {
//                if (addToWS) {
//                    currentWs.add(algorithm);
//                }
//                algoModel.setSelectedAlgorithm(algorithm);
//                setEnableState(true);
//            } else {
//                algComboBox.setSelectedItem(NO_SELECTION);
//                setEnableState(false);
//            }
//        } else {
//            algoModel.setSelectedAlgorithm(null);
//            setEnableState(false);
//        }
    }//GEN-LAST:event_algComboBoxActionPerformed

    private void infoLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLabelMouseExited
//        if (richTooltip != null) {
//            richTooltip.hideTooltip();
//        }
    }//GEN-LAST:event_infoLabelMouseExited

    private void infoLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLabelMouseEntered
//        if (richTooltip == null) {
//            AlgorithmModel algoModel = pc.getAlgorithmModel();
//            if (infoLabel.isEnabled() && algoModel.getSelectedAlgorithm() != null) {
//                richTooltip = buildTooltip(algoModel.getSelectedAlgorithm().getFactory());
//            }
//        }
//        if (richTooltip != null) {
//            richTooltip.showTooltip(infoLabel, evt.getLocationOnScreen());
//        }
    }//GEN-LAST:event_infoLabelMouseEntered

    private void applyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyButtonActionPerformed
//        AlgorithmModel algoModel = pc.getAlgorithmModel();
//        Algorithm algo = algoModel.getSelectedAlgorithm();
//        if (algo != null) {
//            if (algoModel.isRunning()) {
//                executor.cancel(algo);
//            } else {
//                Workspace currentWS = pc.getCurrentWorkspace();
//                if (currentWS.isBusy()) {
//                    DialogDisplayer.getDefault().notify(currentWS.getBusyNotifyDescriptor());
//                } else {
//                    algoModel.setRunning(true);
//                    executor.execute(algo);
//                }
//            }
//        }
    }//GEN-LAST:event_applyButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> algComboBox;
    private javax.swing.JButton applyButton;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JPanel propSheetPanel;
    private javax.swing.JScrollPane scrollPane;
    // End of variables declaration//GEN-END:variables
}
