/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.chemspace.impl;

import java.awt.BorderLayout;
import org.bapedis.core.ui.components.SimpleHTMLReport;
import org.openide.util.NbBundle;

/**
 *
 * @author Loge
 */
public class NetworkReportPanel extends javax.swing.JPanel {

    protected MapperAlgorithm csMapper;
    protected NetworkReport netReport;

    /**
     * Creates new form NetworkReportPanel
     */
    public NetworkReportPanel() {
        initComponents();
    }
    
    public void setUp(MapperAlgorithm csMapper) {
        this.csMapper = csMapper;
        this.netReport = csMapper.getNetworkReport();
        setupReport();
    }    
    
    public void setupReport(){
        centerPanel.removeAll();
        if (netReport != null && !csMapper.isRunning()){
            centerPanel.add( new SimpleHTMLReport(getReport()), BorderLayout.CENTER);
        }
        centerPanel.revalidate();
        centerPanel.repaint();
    }
    
    public String getReport() {
        String report = "<HTML> <BODY> <h1>" + NbBundle.getMessage(NetworkReport.class, "NetworkReport.name") + "</h1> "
                + "<br /><br />"
//                + "<h2> Network settings </h2>"
//                + "<hr>"                
//                + csMapper.getSettingsReport()
//                + "<br /><br />"
                + "<h2> Network measures </h2>"
                + "<hr>"                
                + netReport.getMeasureReport()
                + "</BODY> </HTML>";

        return report;
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        centerPanel.setLayout(new java.awt.BorderLayout());
        add(centerPanel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    // End of variables declaration//GEN-END:variables
}
