/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.filters.impl;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.event.AncestorEvent;
import javax.swing.event.AncestorListener;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.bapedis.core.project.ProjectManager;
import org.bapedis.core.spi.filters.Filter;
import org.bapedis.core.spi.filters.FilterSetupUI;
import org.bapedis.core.spi.filters.impl.DoubleFilterOperator;
import org.bapedis.core.spi.filters.impl.FilterHelper;
import org.bapedis.core.spi.filters.impl.FilterOperator;
import org.bapedis.core.spi.filters.impl.IntegerFilterOperator;
import org.bapedis.core.spi.filters.impl.LongFilterOperator;
import org.gephi.graph.api.Column;
import org.gephi.graph.api.Origin;
import org.gephi.graph.api.Table;
import org.openide.util.Lookup;
import org.openide.util.NbBundle;

/**
 *
 * @author Loge
 */
public class NetworkMeasureFilterSetupUI extends javax.swing.JPanel implements FilterSetupUI {

    protected NetworkMeasureFilter filter;
    protected boolean validState;
    protected final PropertyChangeSupport changeSupport;
    protected final static ProjectManager pc = Lookup.getDefault().lookup(ProjectManager.class);

    /**
     * Creates new form NetworkMeasureFilterSetupUI
     */
    public NetworkMeasureFilterSetupUI() {
        initComponents();
        changeSupport = new PropertyChangeSupport(this);
        validState = false;
        valueTextField.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateValidState();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateValidState();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
        valueTextField.addAncestorListener(new AncestorListener() {

            @Override
            public void ancestorAdded(AncestorEvent event) {
                SwingUtilities.invokeLater(new Runnable() {
                    @Override
                    public void run() {
                        valueTextField.requestFocusInWindow();
                    }
                });
            }

            @Override
            public void ancestorRemoved(AncestorEvent event) {
            }

            @Override
            public void ancestorMoved(AncestorEvent event) {
            }
        });
    }

    private void updateValidState() {
        boolean oldValue = validState;
        validState = true;
        errorLabel.setText("");
        if (attrComboBox.getSelectedIndex() == -1) {
            validState = false;
            errorLabel.setText(NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.errorLabel.invalidAttribute"));
        }
        if (validState && opComboBox.getSelectedIndex() == -1) {
            validState = false;
            errorLabel.setText(NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.errorLabel.invalidOperator"));
        }
        FilterOperator operator = (FilterOperator) opComboBox.getSelectedItem();
        if (validState && (valueTextField.getText().isEmpty()
                || ((operator instanceof IntegerFilterOperator
                || operator instanceof LongFilterOperator
                || operator instanceof DoubleFilterOperator)
                && !operator.isValid(valueTextField.getText())))) {
            validState = false;
            errorLabel.setText(NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.errorLabel.invalidValue"));
        }
        changeSupport.firePropertyChange(VALID_STATE, oldValue, validState);
    }

    protected void initAttrComboBox() {
        attrComboBox.removeAllItems();
        Table nodeTable = pc.getGraphModel().getNodeTable();
        for (Column column : nodeTable) {
            if (column.getOrigin() == Origin.DATA) {
                attrComboBox.addItem(new ComboBoxItem(column));
            }
        }
        if (attrComboBox.getItemCount() > 0) {
            attrComboBox.setSelectedIndex(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        opLabel = new javax.swing.JLabel();
        notCheckBox = new javax.swing.JCheckBox();
        errorLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        attrComboBox = new javax.swing.JComboBox();
        opComboBox = new javax.swing.JComboBox();
        attrLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(126, 90));
        setPreferredSize(new java.awt.Dimension(340, 170));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(opLabel, org.openide.util.NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.opLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        add(opLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(notCheckBox, org.openide.util.NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.notCheckBox.text")); // NOI18N
        notCheckBox.setMargin(new java.awt.Insets(2, 0, 2, 2));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        add(notCheckBox, gridBagConstraints);

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        org.openide.awt.Mnemonics.setLocalizedText(errorLabel, org.openide.util.NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.errorLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        add(errorLabel, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(valueLabel, org.openide.util.NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.valueLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 3);
        add(valueLabel, gridBagConstraints);

        attrComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attrComboBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 3, 0);
        add(attrComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        add(opComboBox, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(attrLabel, org.openide.util.NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.attrLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        add(attrLabel, gridBagConstraints);

        valueTextField.setText(org.openide.util.NbBundle.getMessage(NetworkMeasureFilterSetupUI.class, "NetworkMeasureFilterSetupUI.valueTextField.text")); // NOI18N
        valueTextField.setPreferredSize(new java.awt.Dimension(150, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 3, 0);
        add(valueTextField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void attrComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attrComboBoxActionPerformed
        opComboBox.removeAllItems();
        if (attrComboBox.getSelectedItem() instanceof ComboBoxItem) {
            ComboBoxItem item = (ComboBoxItem) attrComboBox.getSelectedItem();
            FilterOperator[] operators = FilterHelper.getOperators(item.getColumn().getTypeClass());
            for (FilterOperator operator : operators) {
                opComboBox.addItem(operator);
            }
        }
    }//GEN-LAST:event_attrComboBoxActionPerformed

    @Override
    public JPanel getEditPanel(Filter filter) {
        this.filter = (NetworkMeasureFilter) filter;
        notCheckBox.setSelected(this.filter.isNegative());
        initAttrComboBox();
        Column attr = this.filter.getAttribute();
        ComboBoxItem item = (ComboBoxItem) attrComboBox.getSelectedItem();
        if (attr != null && !attr.equals(item.getColumn())) {
            for (int i = 0; i < attrComboBox.getItemCount(); i++) {
                item = (ComboBoxItem) attrComboBox.getItemAt(i);
                if (item.getColumn() == attr) {
                    attrComboBox.setSelectedItem(item);
                }
            }
        }
        FilterOperator operator = this.filter.getOperator();
        if (operator != null && !operator.equals(opComboBox.getSelectedItem())) {
            opComboBox.setSelectedItem(operator);
        }
        String value = this.filter.getValue() != null ? this.filter.getValue() : "";
        if (!value.equals(valueTextField.getText())) {
            valueTextField.setText(value);
        } else {
            updateValidState();
        }
        return this;
    }

    @Override
    public void saveSettings() {
        FilterOperator operator = (FilterOperator) opComboBox.getSelectedItem();
        String operand = valueTextField.getText();
        if (operator.isValid(operand)) {
            filter.setNegative(notCheckBox.isSelected());
            filter.setAttribute(((ComboBoxItem) attrComboBox.getSelectedItem()).getColumn());
            filter.setOperator((FilterOperator) opComboBox.getSelectedItem());
            filter.setValue(valueTextField.getText().trim());
        }

    }

    @Override
    public void cancelSettings() {
        filter = null;
    }

    @Override
    public boolean isValidState() {
        return validState;
    }

    @Override
    public void addValidStateListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    @Override
    public void removeValidStateListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox attrComboBox;
    private javax.swing.JLabel attrLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JCheckBox notCheckBox;
    private javax.swing.JComboBox opComboBox;
    private javax.swing.JLabel opLabel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}

class ComboBoxItem {

    private final Column column;

    public ComboBoxItem(Column column) {
        this.column = column;
    }

    public Column getColumn() {
        return column;
    }

    @Override
    public String toString() {
        return column.getTitle();
    }
}
