/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.filters.impl;

import java.beans.PropertyChangeListener;
import javax.swing.JPanel;
import org.bapedis.core.spi.filters.Filter;
import org.bapedis.core.spi.filters.FilterSetupUI;

/**
 *
 * @author loge
 */
public class PDBFilterSetupUI extends javax.swing.JPanel implements FilterSetupUI {
    
    protected PDBFilter filter;
    /**
     * Creates new form ThreeDFilterSetupUI
     */
    public PDBFilterSetupUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();

        setMinimumSize(new java.awt.Dimension(240, 120));
        setPreferredSize(new java.awt.Dimension(240, 120));
        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PDBFilterSetupUI.class, "PDBFilterSetupUI.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jLabel1, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Available", "Not available", " " }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        add(jComboBox1, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public JPanel getEditPanel(Filter filter) {
        this.filter = (PDBFilter) filter;
        return this;
    }

    @Override
    public boolean isValidState() {
        return true;
    }

    @Override
    public void finishSettings() {
        boolean negative = jComboBox1.getSelectedIndex() == 1;
        filter.setNegative(negative);
    }

    @Override
    public void cancelSettings() {
        filter = null;
    }

    @Override
    public void addValidStateListener(PropertyChangeListener listener) {
        
    }

    @Override
    public void removeValidStateListener(PropertyChangeListener listener) {
        
    }
}
