/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.bapedis.chemspace.spi.impl;

import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.bapedis.chemspace.spi.TwoDTransformer;
import org.bapedis.chemspace.spi.TwoDTransformerSetupUI;
import org.openide.DialogDisplayer;
import org.openide.NotifyDescriptor;
import org.openide.util.NbBundle;

/**
 *
 * @author Home
 */
public class WekaPCATransformerPanel extends javax.swing.JPanel implements TwoDTransformerSetupUI {

    private WekaPCATransformer pcaTransformer;
    private final NotifyDescriptor errorND;

    /**
     * Creates new form WekaPCATransformerPanel
     */
    public WekaPCATransformerPanel() {
        initComponents();
        errorND = new NotifyDescriptor.Message(NbBundle.getMessage(WekaPCATransformerPanel.class, "WekaPCATransformerPanel.errorND"), NotifyDescriptor.ERROR_MESSAGE);

        jVarianceCovered.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                updateVarianceCovered();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateVarianceCovered();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {

            }
        });
    }

    private void updateVarianceCovered() {
        try {
            if (!jVarianceCovered.getText().isEmpty()) {
                double varianceCovered = Double.parseDouble(jVarianceCovered.getText());
                if (pcaTransformer != null && pcaTransformer.getVarianceCovered() != varianceCovered) {
                    pcaTransformer.setVarianceCovered(varianceCovered);
                }
            }
        } catch (NumberFormatException ex) {
            DialogDisplayer.getDefault().notify(errorND);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jVarianceCovered = new javax.swing.JTextField();
        extLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(WekaPCATransformerPanel.class, "WekaPCATransformerPanel.jLabel1.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        add(jLabel1, gridBagConstraints);

        jVarianceCovered.setText(org.openide.util.NbBundle.getMessage(WekaPCATransformerPanel.class, "WekaPCATransformerPanel.jVarianceCovered.text")); // NOI18N
        jVarianceCovered.setMinimumSize(new java.awt.Dimension(90, 27));
        jVarianceCovered.setPreferredSize(new java.awt.Dimension(90, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        add(jVarianceCovered, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(extLabel, org.openide.util.NbBundle.getMessage(WekaPCATransformerPanel.class, "WekaPCATransformerPanel.extLabel.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(extLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public JPanel getSettingPanel(TwoDTransformer transformer) {
        this.pcaTransformer = (WekaPCATransformer) transformer;
        jVarianceCovered.setText(String.valueOf(pcaTransformer.getVarianceCovered()));
        return this;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel extLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jVarianceCovered;
    // End of variables declaration//GEN-END:variables
}
